language: php

php:
  - 5.4

branches:
    only:
        - master

before_script: 
    - composer self-update
    - composer install
    - ./tools/db-init.sh

script: ./vendor/bin/phpunit -c phpunit.xml 

