language: php

php:
  - 5.4

branches:
    only:
        - master

before_script: 
    - composer self-update
    - composer install
    - mkdir data
    - touch data/app.db

script: ./vendor/bin/phpunit -c phpunit.xml 

